name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy backend on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            APP_DIR=~/car-rent-app-backend

            # Remove existing project entirely
            rm -rf $APP_DIR

            # Clone a fresh copy
            git clone https://github.com/Chetanya2001/car-rent-app-backend.git $APP_DIR

            cd $APP_DIR

            # Write .env file from secret
            cat <<EOF > $APP_DIR/.env
            ${{ secrets.BACKEND_ENV_FILE }}
            EOF

            # Install dependencies
            npm install

            # Restart backend process managed by PM2
            pm2 restart server || pm2 start server.js --name server

            pm2 status
